#!/bin/bash
# Production setup script for Render deployment
# Run this before deploying to validate your setup

set -e

echo "🔍 Complicore Production Pre-Flight Check"
echo "========================================="

# Check required files
echo ""
echo "📁 Required files:"
for f in render.yaml requirements.txt Dockerfile .env.prod.example; do
  if [ -f "$f" ]; then
    echo "  ✅ $f"
  else
    echo "  ❌ $f (missing)"
  fi
done

# Check Python dependencies
echo ""
echo "🐍 Python dependencies:"
if [ -f "requirements.txt" ]; then
  for pkg in fastapi uvicorn temporalio sqlalchemy psycopg2-binary python-dotenv pydantic; do
    if grep -qi "$pkg" requirements.txt; then
      echo "  ✅ $pkg"
    else
      echo "  ⚠️  $pkg (not in requirements.txt)"
    fi
  done
fi

# Check Node dependencies
echo ""
echo "📦 Node dependencies:"
if [ -f "package.json" ]; then
  for pkg in next react react-dom; do
    if grep -q "$pkg" package.json; then
      echo "  ✅ $pkg"
    else
      echo "  ❌ $pkg (missing)"
    fi
  done
fi

# Check environment variables
echo ""
echo "🔑 Environment variables to configure in Render:"
echo "  Required:"
echo "    - NEXTAUTH_SECRET (auto-generated by Render)"
echo "    - TEMPORAL_HOST (Temporal Cloud endpoint)"
echo "    - OPENAI_API_KEY (or your LLM provider key)"
echo "    - ANTHROPIC_API_KEY (optional)"
echo "    - GEMINI_API_KEY (optional)"
echo ""
echo "  Auto-configured by Render:"
echo "    - DATABASE_URL (from managed Postgres)"
echo "    - REDIS_URL (from managed Redis)"
echo "    - NEXT_PUBLIC_API_BASE (from API service)"

# Check render.yaml validity
echo ""
echo "📋 Render config:"
if [ -f "render.yaml" ]; then
  SERVICES=$(grep -c "type:" render.yaml)
  echo "  ✅ render.yaml found ($SERVICES services defined)"
else
  echo "  ❌ render.yaml not found"
fi

echo ""
echo "========================================="
echo "🚀 Next steps:"
echo "  1. Push to GitHub: git push origin main"
echo "  2. Connect repo to Render: https://dashboard.render.com"
echo "  3. Import render.yaml"
echo "  4. Set sync: false variables in Render dashboard"
echo "  5. Deploy!"
